export const LIMITS = {
  MAX_CART_ITEMS: 50,
  MAX_ORDER_ITEMS: 100,
  MAX_PRODUCTS_PER_SHOP: 1000,
  MAX_DELIVERY_RADIUS_KM: 25,
  MIN_ORDER_AMOUNT: 0,
  OTP_LENGTH: 6,
  OTP_EXPIRY_MINUTES: 10,
} as const
